config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  resources :users, only: %i[show update edit] do
    member do
      get :following
      get :searches
    end
  end
  get '/settings', to: 'users#edit'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update_email'
    end
  end
  resources :tickets
  resources :categories, only: %i[index show]
  resources :ticket_activations, only: [:edit]
  resources :relationships, only: %i[create destroy]
  resources :searches, only: %i[new show update create destroy] do
    member do
      get :new_tickets
    end
  end

  namespace :admin do
    root to: 'admin#index'
    resources :users, only: %i[index show destroy] do
      member do
        get :following
        get :searches
      end
    end
    resources :tickets, only: %i[index show destroy]
    resources :categories
    resources :relationships, only: %i[index destroy]
    resources :searches, only: %i[index show destroy] do
      member do
        get :new_tickets
      end
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'Ticket'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/admin/relationships_controller.rb
# frozen_string_literal: true

class Admin::RelationshipsController < Admin::AdminController
  helper_method :sort_column_relationships, :sort_direction

  def index
    @relationships = Relationship.order(sort_column_relationships + ' ' + sort_direction).paginate(page: params[:page])
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    flash[:success] = 'Relationship destroyed'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @ticket = Ticket.find(params[:followed_id])
    current_user.follow(@ticket)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  def destroy
    @ticket = Relationship.find(params[:id]).followed
    current_user.unfollow(@ticket)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  def logged_in_user
    redirect_to new_user_session_path if current_user.nil?
  end
end

app/helpers/admin/relationships_helper.rb
# frozen_string_literal: true

module Admin::RelationshipsHelper
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper
end

app/views/admin/relationships/_relationship.html.haml
%tr.admin-tr
  %td.admin-td 
    = relationship.id
  %td.admin-td 
    = relationship.created_at
  %td.admin-td 
    = relationship.updated_at
  %td.admin-td 
    = link_to relationship.follower_id, admin_user_path(relationship.follower_id)
  %td.admin-td 
    = link_to relationship.followed_id, admin_ticket_path(relationship.followed_id)
  %td 
    = link_to 'delete', admin_relationship_path(relationship), method: :delete

app/views/admin/relationships/index.html.haml
%table(style="width:100%" border="1|0")
  = will_paginate
  %tr
    %th
      = sortable('id', 'id', 'relationships')
    %th
      = sortable('created_at', 'created_at', 'relationships')
    %th
      = sortable('updated_at', 'updated_at', 'relationships')
    %th
      = sortable('follower_id', 'Follower_id (user)', 'relationships')
    %th
      = sortable('followed_id','Followed_id (ticket)', 'relationships')
    %th action
  = render @relationships