config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  resources :users, only: %i[show update edit] do
    member do
      get :following
      get :searches
    end
  end
  get '/settings', to: 'users#edit'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update_email'
    end
  end
  resources :tickets
  resources :categories, only: %i[index show]
  resources :ticket_activations, only: [:edit]
  resources :relationships, only: %i[create destroy]
  resources :searches, only: %i[new show update create destroy] do
    member do
      get :new_tickets
    end
  end

  namespace :admin do
    root to: 'admin#index'
    resources :users, only: %i[index show destroy] do
      member do
        get :following
        get :searches
      end
    end
    resources :tickets, only: %i[index show destroy]
    resources :categories
    resources :relationships, only: %i[index destroy]
    resources :searches, only: %i[index show destroy] do
      member do
        get :new_tickets
      end
    end
  end
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :relationships, foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :relationships, source: :follower
  before_create :create_activation_digest
  mount_uploader :picture, PictureUploader
  attr_accessor :user_attributes, :activation_token
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 4096 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :ticket_type, presence: true
  validates :location, length: { maximum: 50 }, presence: true
  validate :picture_size
  validate :not_main_category

  def not_main_category
    errors.add(:category_id, 'should choose subcategory') if category.main?
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end

  def find_next(up_at, cat_id)
    Ticket.where('updated_at < ? and category_id = ? ', up_at, cat_id).order(updated_at: :desc).first || nil
  end

  def find_previous(up_at, cat_id)
    Ticket.where('updated_at > ? and category_id = ? ', up_at, cat_id).order(updated_at: :desc).last || nil
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(activation_token)
    digest = send('activation_digest')
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(activation_token)
  end

  def send_activation_email
    TicketMailer.ticket_activation(self).deliver_now
  end

  def activate
    update_attributes(activated: true, activated_at: Time.zone.now)
  end

  def self.activated
    where(activated: true)
  end

  def self.has_picture
    where.not(picture: nil)
  end

  private

  def create_activation_digest
    self.activation_token = Ticket.new_token
    self.activation_digest = Ticket.digest(activation_token)
  end
end

app/controllers/admin/tickets_controller.rb
# frozen_string_literal: true

class Admin::TicketsController < Admin::AdminController
  helper_method :sort_column_tickets, :sort_direction
  def index
    @tickets = Ticket.order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
  end

  def show
    @ticket = Ticket.find(params[:id])
    @next_ticket = @ticket.find_next(@ticket.updated_at, @ticket.category_id)
    @previous_ticket = @ticket.find_previous(@ticket.updated_at, @ticket.category_id)
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    flash[:success] = 'Announcement deleted'
    redirect_to admin_user_path(current_user)
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]
  before_action :update_contact, only: %i[create update]

  def index
    @tickets = Ticket.where(activated: true).paginate(page: params[:page])
  end

  def show
    @ticket = Ticket.find(params[:id])
    @next_ticket = @ticket.find_next(@ticket.updated_at, @ticket.category_id)
    @previous_ticket = @ticket.find_previous(@ticket.updated_at, @ticket.category_id)
    redirect_to(root_url) && return unless @ticket.activated?
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)
    if @ticket.save
      @ticket.send_activation_email
      flash[:info] = 'Please check your mail to activate your ticket.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @ticket.update_attributes(ticket_params)
      flash[:success] = 'Announcement updated'
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket.destroy
    flash[:success] = 'Announcement deleted'
    redirect_to user_path(current_user)
  end

  def update_contact
    @user = current_user
    @user.name = ticket_params[:user_attributes][:name]
    @user.phone = ticket_params[:user_attributes][:phone]
    @user.validate_name = true
    redirect_back(fallback_location: root_path) unless @user.save
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :content, :price, :ticket_type, :location, :category_id, :picture, user_attributes: %i[name phone])
  end

  def correct_user
    @ticket = current_user.tickets.find_by(id: params[:id])
    redirect_to root_url if @ticket.nil?
  end
end

app/helpers/admin/tickets_helper.rb
# frozen_string_literal: true

module Admin::TicketsHelper
end

app/helpers/tickets_helper.rb
# frozen_string_literal: true

module TicketsHelper
end

app/views/admin/tickets/_ticket.html.haml
%tr.admin-tr
  %td.admin-td
    = link_to ticket.id, admin_ticket_path(ticket) 
  %td.admin-td
    = link_to ticket.title, admin_ticket_path(ticket) 
  %td.admin-td
    = link_to ticket.price, admin_ticket_path(ticket) 
  %td.admin-td
    = link_to ticket.ticket_type, admin_ticket_path(ticket) 
  %td.admin-td
    = link_to ticket.location, admin_ticket_path(ticket) 
  %td.admin-td
    -  if ticket.picture.present?
      = link_to ticket.picture, admin_ticket_path(ticket)
  %td.admin-td
    -  if ticket.created_at.present?
      = link_to ticket.created_at.to_s(:db), admin_ticket_path(ticket)
  %td.admin-td
    - if ticket.updated_at.present? 
      = link_to ticket.updated_at.to_s(:db), admin_ticket_path(ticket)
  %td.admin-td
    - if ticket.activated.present?
      = link_to ticket.activated, admin_ticket_path(ticket) 
  %td.admin-td
    - if ticket.activated_at.present? 
      = link_to ticket.activated_at.to_s(:db), admin_ticket_path(ticket)
  %td.admin-td
    = link_to ticket.category.text, admin_category_path(ticket.category)
    main:
    = link_to ticket.category.main.text, admin_category_path(ticket.category.main) 
  %td.admin-td
    = link_to ticket.user_id, admin_user_path(ticket.user) 
  %td
    = link_to 'delete', admin_ticket_path(ticket), method: :delete   

app/views/admin/tickets/_ticket_columns.html.haml
%table(style="width:100%" border="1|0")
  = will_paginate @tickets
  %tr
    %th
      = sortable('id', 'id', 'tickets')
    %th
      = sortable('title', 'title', 'tickets')
    %th
      = sortable('price', 'price', 'tickets')
    %th
      = sortable('ticket_type', 'ticket_type', 'tickets')
    %th
      = sortable('location', 'location', 'tickets')
    %th
      = sortable('picture', 'picture', 'tickets')
    %th
      = sortable('created_at', 'created_at', 'tickets')
    %th
      = sortable('updated_at', 'updated_at', 'tickets')
    %th
      = sortable('activated', 'activated', 'tickets')
    %th
      = sortable('activated_at', 'activated_at', 'tickets')
    %th
      = sortable('category', 'category_id', 'tickets')
    %th
      = sortable('user_id', 'user_id', 'tickets')
    %th
      action
  = render @tickets
= will_paginate @tickets

app/views/admin/tickets/index.html.haml
- provide(:title, 'All tickets')
%h1
  All tickets
= render 'ticket_columns'

app/views/admin/tickets/show.html.haml
- provide(:title, "Ticket")
%div.container
  %div.row.pricing
    %div.col-md-10
      %div.well
        %p
          = link_to 'All categories', admin_categories_path
          |
          = link_to @ticket.category.main.text, admin_category_path(@ticket.category.main)
          >>
          = link_to @ticket.category.text, admin_category_path(@ticket.category)
        %hr
        - unless @previous_ticket.nil?
          %p.btn.btn-default.left
            = link_to "previous", admin_ticket_path(@previous_ticket)
        - unless @next_ticket.nil?
          %p.btn.btn-default.right
            = link_to "next", admin_ticket_path(@next_ticket)
        %br
        %br
        %p.center
          - if @ticket.picture?
            = image_tag avatar_url(@ticket), size: 400
          
        %hr
        %p
          = @ticket.created_at.to_formatted_s(:long)
          Location:
          = @ticket.location
          type:
          = @ticket.ticket_type
        %h1
          %b
            = @ticket.title
        %hr
          = @ticket.content

    %div.col-md-2
      %div.well
        %h3
          %b
            = @ticket.price
        %hr
        %p
        = link_to @ticket.user.name, admin_user_path(@ticket.user)
        %hr
        - if @ticket.user.phone?
          %p
            Phone: 
            = @ticket.user.phone
        %hr
        %p
          Followers: 
          = @ticket.followers.count

= link_to "delete", admin_ticket_path(@ticket), method: :delete, data: { confirm: "You sure?" }