config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  resources :users, only: %i[show update edit] do
    member do
      get :following
      get :searches
    end
  end
  get '/settings', to: 'users#edit'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update_email'
    end
  end
  resources :tickets
  resources :categories, only: %i[index show]
  resources :ticket_activations, only: [:edit]
  resources :relationships, only: %i[create destroy]
  resources :searches, only: %i[new show update create destroy] do
    member do
      get :new_tickets
    end
  end

  namespace :admin do
    root to: 'admin#index'
    resources :users, only: %i[index show destroy] do
      member do
        get :following
        get :searches
      end
    end
    resources :tickets, only: %i[index show destroy]
    resources :categories
    resources :relationships, only: %i[index destroy]
    resources :searches, only: %i[index show destroy] do
      member do
        get :new_tickets
      end
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subcategories, class_name: 'Category',
                           foreign_key: 'main_id',
                           dependent: :destroy
  belongs_to :main, optional: true, class_name: 'Category'

  has_many :tickets
  validates :text, presence: true, length: { maximum: 30 }
  before_save { text.downcase! }

  def main?
    main_id.nil?
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::AdminController
  helper_method :sort_column_tickets, :sort_direction

  def index
    @categories = Category.where(main_id: nil).all
    @tickets = Ticket.order(activated_at: :desc).paginate(page: params[:page])
  end

  def show
    @pre_select = params[:id]
    @category = Category.find(params[:id])
    if @category.main?
      @tickets = Ticket.where(category: @category.subcategories).order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    else
      @tickets = Ticket.where(category: @category).order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = 'New category created!'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(categories_params)
      flash[:success] = 'Category updated'
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = 'Category deleted'
    redirect_to admin_categories_path
  end

  private

  def categories_params
    params.require(:category).permit(:text, :main_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  helper_method :sort_column_tickets, :sort_direction

  def index
    @categories = Category.where(main_id: nil).all
    @tickets = Ticket.activated.order(activated_at: :desc).limit(15)
  end

  def show
    @pre_select = params[:id]
    @category = Category.find(params[:id])
    if @category.main?
      @tickets = Ticket.activated.where(category: @category.subcategories).order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    else
      @tickets = Ticket.activated.where(category: @category).order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    end
  end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/admin/categories/_category_form.html.haml
%div.row
  %div.col-md-6.col-md-offset-3
    = form_for ([:admin, @category]) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :text
      =f.text_field :text, autocomplete: "on" , class: 'form-control'
      %br
      = f.label :main
      = f.collection_select(:main_id, Category.where(main_id: nil).all, :id, :text, include_blank: true)
      %br
      %br
      = f.submit yield(:btn_text), class: "btn btn-primary"

app/views/admin/categories/edit.html.haml
=provide(:title, "Update category")
=provide(:btn_text, "Update category")
%h1 Update category
= render 'category_form'

app/views/admin/categories/index.html.haml
= render 'searches/simple_search'
%div.cat
  - @categories.each do |main|
    %div.btn.btn-default
      %table
        %thead
          %tr
            %td.centert(colspan = "#{main.subcategories.count}")
              = link_to main.text, admin_category_path(main)
        %tbody
          %tr
            - main.subcategories.each do |subcategory|
              %td.centert 
                = link_to subcategory.text, admin_category_path(subcategory)
              
          
      
  = link_to 'Add category', new_admin_category_path, class: "btn btn-default"
%h3 LATEST TICKETS
= render 'admin/tickets/ticket_columns'

app/views/admin/categories/new.html.haml
= provide(:title, "Add category")
= provide(:btn_text, "Add category")
%h1 Add category
= render 'category_form'

app/views/admin/categories/show.html.haml
= render 'searches/search_form'
%h5
  Sort by: 
  = sortable('activated_at', 'latest', 'tickets')
  = sortable('price', 'price', 'tickets')
= @category.text 
= link_to 'edit', edit_admin_category_path(@category)
= link_to 'delete', admin_category_path(@category), method: :delete
%div.panel.panel-default.panel-table
  %div.panel-heading
    %div.row
      %div.col.col-xs-6
        %h3.panel-title 
          = link_to 'All categories', categories_path
          |
          - if @category.main?
            = @category.text
            >>
            - @category.subcategories.each do |subcategory|
              = link_to subcategory.text, admin_category_path(subcategory)
          - else
            = link_to(@category.main.text, admin_category_path(@category.main))
            <<
            = @category.text
      
  %div.panel-body
    = render 'admin/tickets/ticket_columns'