config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  resources :users, only: %i[show update edit] do
    member do
      get :following
      get :searches
    end
  end
  get '/settings', to: 'users#edit'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update_email'
    end
  end
  resources :tickets
  resources :categories, only: %i[index show]
  resources :ticket_activations, only: [:edit]
  resources :relationships, only: %i[create destroy]
  resources :searches, only: %i[new show update create destroy] do
    member do
      get :new_tickets
    end
  end

  namespace :admin do
    root to: 'admin#index'
    resources :users, only: %i[index show destroy] do
      member do
        get :following
        get :searches
      end
    end
    resources :tickets, only: %i[index show destroy]
    resources :categories
    resources :relationships, only: %i[index destroy]
    resources :searches, only: %i[index show destroy] do
      member do
        get :new_tickets
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :tickets, dependent: :destroy
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :relationships, source: :followed
  has_many :searches, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true, allow_nil: true
  validates :name, presence: true, if: :validate_name?
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 225 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :phone, length: { maximum: 15 }
  attr_accessor :validate_name

  def validate_name?
    validate_name == 'true' || validate_name == true
  end

  def follow(ticket)
    following << ticket
  end

  def unfollow(ticket)
    following.delete(ticket)
  end

  def following?(ticket)
    following.include?(ticket)
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::AdminController
  include UsersHelper
  helper_method :sort_column_users, :sort_direction, :sort_column_tickets

  def index
    @users = User.order(sort_column_users + ' ' + sort_direction).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tickets = @user.tickets.order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_path
  end

  def following
    @user = User.find(params[:id])
    if @user.nil?
      redirect_to root_path
    else
      @tickets = @user.following.paginate(page: params[:page])
    end
  end

  def searches
    @user = User.find(params[:id])
    if @user.nil?
      redirect_to root_path
    else
      @user_searches = @user.searches.paginate(page: params[:page])
      render 'searches'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  helper_method :sort_column_tickets, :sort_direction
  include UsersHelper

  def show
    @user = User.find(params[:id])
    @user_id = @user.id
    if @user == current_user
      @tickets = @user.tickets.order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    else
      @tickets = Ticket.activated.where(user_id: @user.id).order(sort_column_tickets + ' ' + sort_direction).paginate(page: params[:page])
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    params[:user][:name] = nil if params[:user][:name] == ''
    params[:user][:phone] = nil if params[:user][:phone] == ''

    if @user.update_attributes(user_params)
      after_update('Profile updated')
    else
      redirect_to edit_user_path(@user)
    end
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(user_password_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      after_update('Password updated')
    else
      redirect_to edit_user_path(@user)
    end
  end

  def update_email
    @user = User.find(current_user.id)
    if @user.update(user_email_params)
      after_update('Email updated')
    else
      redirect_to edit_user_path(@user)
    end
  end

  def following
    @user = current_user
    if @user.nil?
      redirect_to root_path
    else
      @tickets = @user.following.paginate(page: params[:page])
    end
  end

  def searches
    @user = current_user
    if @user.nil?
      redirect_to root_path
    else
      @user_searches = @user.searches.paginate(page: params[:page])
      render 'searches'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone)
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end

  def user_email_params
    params.require(:user).permit(:email)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_update(message)
    flash[:success] = message
    redirect_to edit_user_path(@user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_update(message)
    flash[:success] = message
    redirect_to edit_user_path(@user)
  end
end

app/views/admin/users/_table_show.html.haml
%table
  - User.column_names.each do |column_name|
    %tr
      %td
        = column_name
      %td
        = @user.send(column_name)

= link_to 'delete user', admin_user_path(@user), method: :delete 
= link_to 'user tickets', admin_user_path(@user) 
= link_to 'user following tickets', following_admin_user_path(@user) 
= link_to 'user searches', searches_admin_user_path(@user) 

app/views/admin/users/_user.html.haml
%tr.admin-tr
  %td.admin-td
    = link_to user.id, admin_user_path(user)
  %td.admin-td
    = link_to user.email, admin_user_path(user)
  %td.admin-td
    - if user.name.present?
      = link_to user.name, admin_user_path(user)
  %td.admin-td
    - if user.phone.present?
      = link_to user.phone, admin_user_path(user)  
  %td.admin-td
    - if user.admin.present?
      = link_to user.admin, admin_user_path(user) 
  %td.admin-td
    - if user.created_at.present?
      = link_to user.created_at.to_s(:db), admin_user_path(user)  
  %td.admin-td
    - if user.updated_at.present?
      = link_to user.updated_at.to_s(:db), admin_user_path(user)   
  %td.admin-td
    - if user.confirmed_at.present?
      = link_to user.confirmed_at.to_s(:db), admin_user_path(user)   
  %td.admin-td
    - if user.unconfirmed_email.present?
      = link_to user.unconfirmed_email, admin_user_path(user) 
  %td
    = link_to 'delete', admin_user_path(user), method: :delete

app/views/admin/users/following.html.haml
= render 'table_show'
= render 'admin/tickets/ticket_columns'

app/views/admin/users/index.html.haml
- provide(:title, 'All users')
%h1
  All users
%table(style="width:100%" border="1|0")
  = will_paginate
  %tr
    %th
      = sortable('id', 'id', 'users')
    %th
      = sortable('email', 'email', 'users') 
    %th
      = sortable('name', 'name', 'users')
    %th
      = sortable('phone', 'phone', 'users') 
    %th
      = sortable('admin', 'admin', 'users')
    %th
      = sortable('created_at', 'created_at', 'users') 
    %th
      = sortable('updated_at', 'updated_at', 'users')
    %th
      = sortable('confirmed_at', 'confirmed_at', 'users')
    %th
      = sortable('unconfirmed_email', 'unconfirmed_email', 'users')
    %th
      action
  = render @users
= will_paginate

app/views/admin/users/searches.html.haml
= render 'table_show' 
%div.panel.panel-default.panel-table
  %div.panel-heading
    %div.row
      %div.col.col-xs-6
        %h3.panel-title
          = @user.name
        %br
          Following searches
  %div.panel-body
    %table.table.table-striped.table-bordered.table-list
      %tbody
        - @user_searches.each do |search| 
          %tr
            - if search.keywords.present? 
              %br
                Keywords: #{search.keywords}

            - if search.in_content?    
              %br
                searched in content 

            - if search.with_picture?  
              %br
                only with picture 

            - if search.location_keywords.present? 
              %br
                Location:
                = search.location_keywords

            - if search.category_id.present? 
              %br
                Category:
                = Category.find(search.category_id).text 

            - if search.minimum_price.present? 
              %br  
              Price from:
              = search.minimum_price 

            - if search.maximum_price.present? 
              %br
              Price to: 
              = search.maximum_price

            - if search.type_of_ticket.present? 
              %br
                Type of ticket:
                = search.type_of_ticket 

            %br
              Searched:
              = time_ago_in_words(search.created_at)
              ago.
            %hr
            - if search.new_tickets.any? 
              %a.btn.btn-warning{href: new_tickets_admin_search_path(search)}
                Show new tickets
              %span.badge
                = search.new_tickets.count
              &nbsp
            - else
              = link_to "Show all tickets", admin_search_path(search), class: "btn btn-primary"
              &nbsp
           
            = link_to "delete", admin_search_path(search), method: :delete, class: "btn btn-danger" 
            %hr
    

app/views/admin/users/show.html.haml
= render 'table_show'
= render 'admin/tickets/ticket_columns'